```mermaid
graph LR
  stop_times["stop_times (500 samples)"]
  routes["routes (176 samples)"]
  calendar["calendar (18 samples)"]
  feed_info["feed_info (1 samples)"]
  transfers["transfers (500 samples)"]
  stops["stops (500 samples)"]
  agency["agency (1 samples)"]
  translations["translations (500 samples)"]
  calendar_dates["calendar_dates (0 samples)"]
  trips["trips (500 samples)"]
  shapes["shapes (500 samples)"]
```